version: "3"
services:
  bitcoind:
    container_name: bitcoind
    build:
      dockerfile: bitcoind.dockerfile
      context: .
    ports:
      - "18443:18443"
      - "18444:18444"
      - "28332:28332"
      - "28333:28333"
    healthcheck:
      test: ["CMD", "curl", "-X", "-f", "http://127.0.0.1:18443/"]
      interval: 30s
      timeout: 10s
      retries: 5
  ord:
    container_name: ord
    build:
      dockerfile: ord.dockerfile
      context: .
    depends_on:
      - bitcoind
    ports:
      - "8000:8000"
      - "8001:8001"

  evm-rpc-canister-proxy:
    container_name: evm-rpc-canister-proxy
    build:
      dockerfile: evm-rpc-canister-proxy.dockerfile
      context: .
    ports:
      - "8002:8002"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  bitcoin-data:
