name: test

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup docker containers
              run: cd btc-deploy/ && docker-compose up -d --build && cd ..
            - name: Run test
              run: ./test.sh
